[package]
name = "dota-timer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"]}
serde = {version = "1.0.216", features = ["derive"]}
serde_yaml = "0.9.33"
rodio = "0.20.1 "

